name: Scheduled Workflow

on:
  schedule:
    - cron: '0 * * * *'  # This runs at the start of every hour

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Execute script or command
        run: echo "This workflow runs every 5 minutes."
