name: Publish Package

on:
  workflow_dispatch:

# jobs:
#   trigger-pipeline:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Azure Pipeline
#         uses: Azure/pipelines@v1
#         with:
#           azure-devops-project-url: "https://dev.azure.com/adityakavale/adityakavale"
#           azure-pipeline-name: "dp-test-org-1.beachball-testing"
#           azure-devops-token: ${{ secrets.PAT_EXTENSION_SERVICE }}
#           azure-pipeline-variables: '{"IS_DEV": true}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Azure Pipeline
        uses: azure/pipelines@v1
        with:
          azure-devops-project-url: "https://dev.azure.com/adityakavale/adityakavale"
          azure-pipeline-name: "dp-test-org-1.beachball-testing"
          azure-devops-token: ${{ secrets.PAT_EXTENSION_SERVICE }}
          parameters: |
            environment: 'prod'
