name: Publish Package

on:
  workflow_dispatch:
    inputs:
      environment:
        type: boolean
        description: Deploy to dev environment

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Azure DevOps
        run: |
          az devops configure --defaults organization=https://dev.azure.com/adityakavale project=adityakavale
          az pipelines run --name "dp-test-org-1.beachball-testing" --branch $(echo ${GITHUB_REF#refs/heads/}) --parameters dev=${{ github.event.inputs.environment }}
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.PAT_EXTENSION_SERVICE }}

      # - uses: Azure/pipelines@v1.2
      #   with:
      #     azure-devops-project-url: "https://dev.azure.com/adityakavale/adityakavale"
      #     azure-pipeline-name: "dp-test-org-1.beachball-testing"
      #     azure-devops-token: ${{ secrets.PAT_EXTENSION_SERVICE }}
      #     azure-pipeline-variables: '{"IS_DEV": "true"}'
