name: Publish Package

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "Environment to deploy to"
        required: true
        default: "dev"
        options:
          - "dev"
          - "prod"

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: "https://dev.azure.com/adityakavale/adityakavale"
          azure-pipeline-name: "dp-test-org-1.beachball-testing"
          azure-devops-token: ${{ secrets.PAT_EXTENSION_SERVICE }}
          azure-pipeline-variables: '{"IS_DEV": "true"}'
