name: Automated PR and Auto-merge

on:
  workflow_dispatch:
    inputs:
      environment:
        type: boolean
        description: Deploy to dev environment

jobs:
  create-pr-and-automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create a new branch and commit changes
        run: |
          git config user.name "Adu21"
          git config user.email "adityakavale21@gmail.com"
          git checkout -b feature/automated-change
          echo "Automated update content" >> automated-file.txt
          git add automated-file.txt
          git commit -m "Automated: Add automated-file.txt"
          git push origin feature/automated-change

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT_FOR_PULL_REQUEST }}
          commit-message: "Automated: Update automated-file.txt via GitHub Actions"
          title: "Automated PR: Update automated-file.txt"
          body: |
            This PR is automatically generated by GitHub Actions to update `automated-file.txt`.
          base: main # Target branch
          branch: feature/automated-change # Source branch
          labels: |
            automerge

      - name: Enable Auto-merge on the PR
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GH_PAT_FOR_PULL_REQUEST }}
          pull-request-number: ${{ github.event.number }}
