name: Role Restriction Test

on:
  workflow_dispatch:

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Role Restriction Test
        if: github.actor == 'Adu2120'
        run: echo ${{ github.actor }}
