name: Scheduled Workflow2

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run the workflow every 5 minutes

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Execute script or command
        run: echo "This workflow runs every 5 minutes."
