name: test gh workflows

# Run this workflow manually from github actions and as per following schedule.
# Scheduled it to run on specific days of the week (Monday, Wednesday, Friday) at 5:30 AM UTC (11am IST).
on:
  schedule:
    - cron: "0 8 * * 1,3,5"

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: set branch name according to release strategy
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "schedule trigger"
            day=$(date +%d)
            if [ "$day" -ge 1 ] && [ "$day" -le 14 ]; then
              echo "BRANCH_NAME=refs/heads/main" >> $GITHUB_ENV
              echo "OPENSITEPLUS_BRANCH=main" >> $GITHUB_ENV
            elif [ "$day" -ge 15 ] && [ "$day" -le 31 ]; then
              echo "BRANCH_NAME=refs/heads/release/current" >> $GITHUB_ENV
              echo "OPENSITEPLUS_BRANCH=release/current" >> $GITHUB_ENV
              echo "environment=false" >> $GITHUB_ENV
              echo "package_to_publish=all" >> $GITHUB_ENV
            fi            
          else
            echo "manual trigger"
            echo "BRANCH_NAME=${{ github.ref }}" >> $GITHUB_ENV
          fi
      - name: debug info
        run: |
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"
          echo "OPENSITEPLUS_BRANCH=${{ env.OPENSITEPLUS_BRANCH }}"
          echo "environment=${{ env.environment }}"
          echo "package_to_publish=${{ env.package_to_publish }}"
